### PR TITLE
Astro 3104

### PR DESCRIPTION
**Pull request by markacianfrani**
Creates border width tokens and a component level token for Standby Status Symbol. 

Giving the 1px token the name 'xs' for now. We might need to readjust it later

### CODE REVIEW

**Comment by markacianfrani** [comment]
@amalyah I think we can remove the borderWidth.standby in light theme now right? I can change that and merge if you wanna merge this in

**Comment by amalyah** [comment]
> 

The use of different colored Status Symbols on dark vs. light backgrounds is already present in the 6.0 and 7.0 files. Since it was a quick change a while ago we're basically using the light theme version of status symbols on light backgrounds and the dark theme version of status symbols on dark backgrounds. We're hoping to simplify this in the future with some redesigns, but right now the color contrast tests wouldn't pass properly with the normal dark status symbol versions on all backgrounds in the dark theme (vice versa in the light theme). Example: Tree hover backgrounds since it uses the interactive hover color as a background.

**Comment by amalyah** [comment]
> @amalyah I think we can remove the borderWidth.standby in light theme now right? I can change that and merge if you wanna merge this in

@markacianfrani Yeah, that's fine with me.

**Review by amalyah — APPROVED** [review]

**Comment by steveg-rocket** [comment]
> 



> > @amalyah So it looks like you changed this border color in the dark theme for status symbol border colors. However, the fill colors didn't change, like our normal light theme fill colors do. Are we making this an official Astro change, where status symbols might appear on light backgrounds in the dark theme?
> 
> @steveg-rocket The use of different colored Status Symbols on dark vs. light backgrounds is already present in the 6.0 and 7.0 files. Since it was a quick change a while ago we're basically using the light theme version of status symbols on light backgrounds and the dark theme version of status symbols on dark backgrounds. We're hoping to simplify this in the future with some redesigns, but right now the color contrast tests wouldn't pass properly with the normal dark status symbol versions on all backgrounds in the dark theme (vice versa in the light theme). Example: Tree hover backgrounds since it uses the interactive hover color as a background.

@amalyah @markacianfrani  Okay, I wasn't aware that's how we wanted to handle things. I was just under the impression that we had a version of dark theme symbols and light theme symbols, and that's when they were used. If this is the case, there are probably other  instances where this could be used as well (like text.white and text.dark). But I am concerned about the fill colors not changing. Since it's hard to see all of these new on-dark and on-light tokens together, I think maybe a review meeting might be helpful. Changing them in Github without a real review is proving difficult to understand.

**Pull request merged**
